#
# eiam-portal - Employee Identity and Access Management
# Copyright © 2022-Present Charles Network Technology Co., Ltd.
#

# spring
spring:
  application:
    name: TOPIAM 企业数字身份管控平台门户端
  jackson:
    #日期格式化
    date-format: "yyyy-MM-dd HH:mm:ss"
    #设置空如何序列化
    default-property-inclusion: NON_NULL
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现单引号
      allow_single_quotes: true
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
    serialization:
      #忽略无法转换的对象
      fail_on_empty_beans: false
      #格式化输出
      indent_output: true
  mvc:
    formcontent:
      filter:
        enabled: true
  cache:
    type: redis
    redis:
      key-prefix: 'topiam'
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  session:
    redis:
      namespace: ${spring.cache.redis.key-prefix}:session
      flush-mode: immediate
      repository-type: indexed
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/topiam?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: eiam
  #elasticsearch
  elasticsearch:
    socket-timeout: 30000s
    connection-timeout: 10000s
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    #reids
    redis:
      host: 127.0.0.1
      port: 6379
      database: 9
      lettuce:
        pool:
          max-idle: 7
          min-idle: 2
          max-active: 7
          max-wait: -1ms
        shutdown-timeout: 200ms
      timeout: 5000ms
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
  main:
    banner-mode: off
#日志配置
logging:
  config: classpath:config/logback-spring.xml
server:
  port: 1989
  shutdown: graceful
  #开启压缩 提高响应速度 减少带宽压力
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024
  servlet:
    session:
      cookie:
        secure: true
        same-site: none
        name: topiam-employee-portal-cookie
        http-only: true
    encoding:
      charset: UTF-8
  #错误处理
  error:
    include-stacktrace: never
    include-exception: true
    include-message: always
    include-binding-errors: never
  # undertow
  undertow:
    threads:
      io: 32
      worker: 256
    buffer-size: 1024
# springdoc
springdoc:
  swagger-ui:
    csrf:
      enabled: true
      cookie-name: 'topiam-csrf-cookie'
      header-name: 'topiam-csrf'
    enabled: false
  cache:
    disabled: true
  writer-with-default-pretty-printer: true